name: universal_chatbot
description: "The Universal LLM Chatbot package is a comprehensive solution that enables developers to integrate various AI services seamlessly into Flutter applications. With this package, you can harness the power of cutting-edge language models and image generation capabilities from renowned AI providers such as OpenAI, Anthropic, Gemini, and more, all within a single, unified interface"
version: 0.0.2
homepage: https://github.com/bookbot-kids/chatbot
repository: https://github.com/bookbot-kids/chatbot
issue_tracker: https://github.com/bookbot-kids/chatbot/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  chat_gpt_sdk: ^3.1.4
  collection: ^1.19.0
  anthropic_sdk_dart: ^0.2.0+1
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_dotenv: ^5.2.1

flutter: