name: chatbot
description: "A chat bot api library."
version: 0.0.2
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  chat_gpt_sdk: ^3.0.9
  anthropic_dart: ^1.0.1
  collection: ^1.19.0

dependency_overrides:
  collection: ^1.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_dotenv: ^5.1.0

flutter: